### ISSUE TITLE
Merge ROKerbalism configs into ROKerbalism

### ISSUE THREAD

**Issue by StonesmileGit** [SpaceODY/Space-Shuttle-System-Expanded#2]
Would you be interested in having configs for SSS added to ROKerbalism? If that is done, you should be able to delete the [RO folder](https://github.com/SpaceODY/Space-Shuttle-System-Expanded/tree/main/RealismOverhaul/RO_SuggestedMods/SpaceShuttleSystem) from the repository.

**Comment by SpaceODY** [comment]
I'll need to rebalance it a bit since I believe it is the issue for Re-Entry not being so stable anymore but yeah im intrested.

**Comment by StonesmileGit** [comment]
Kerbalism configs for SSS have now been added to ROKerbalism, FYI
