### ISSUE TITLE
Put SSTUTools.dll in its own separate folder

### ISSUE THREAD

**Issue by giuliodondi** [SpaceODY/Space-Shuttle-System-Expanded#4]
As the title says. The reason I suggest this change is to avoid problems in case somebody has SSTU installed alongside the SSS, to prevent two SSTUToools.dll from existing in the same GameData at once.
It may cause conflicts difficult to diagnose if someone doesn't know where to look.

**Comment by SpaceODY** [comment]
Alright, i'll change it to a separate folder.
